---

- hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - starter
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - php-xdebug # todo: replace with geerlingguy.php-xdebug when its fixed
#    - perlmonkey.mailcatcher # todo: This is broken
    - oracle-client
    - oracle-php
    - phpbb
  sudo: yes # yolo
