---
- name: Download Xdebug.
  get_url: >
    url=http://xdebug.org/files/xdebug-{{ php_xdebug_version }}.tgz
    dest={{ workspace }}

- name: Untar Xdebug.
  command: >
    tar -C {{ workspace }} -xvzf {{ workspace }}/xdebug-{{ php_xdebug_version }}.tgz
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}/README

- name: Build Xdebug.
  shell: >
    {{ item }}
    chdir={{ workspace }}/xdebug-{{ php_xdebug_version }}
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so
  with_items:
    - phpize
    - ./configure
    - make
  notify: restart apache

- name: Ensure modules directory exists
  file: path={{ php_xdebug_module_path }} state=directory

- name: Move Xdebug module into place.
  shell: >
    cp {{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so {{ php_xdebug_module_path }}/xdebug.so
    creates={{ php_xdebug_module_path }}/xdebug.so

- name: Copy xdebug INI into php.d folder.
  template: >
    src=xdebug.ini.j2
    dest=/etc/php5/conf.d/xdebug.ini
    owner=root group=root mode=644
  notify: restart apache

- debug: var=ansible_os_family